[general]
admin = 123456789 # Replace me!
prefix = "$"
cooldowntime = 0
noreplylist = "data/noreplyusers.json"
neverreplylist = "data/neverreplyusers.json"
allowedchannels = "data/allowedchannels.json"
allowedusers = "data/allowedusers.json"

[channels]
report-users-channel-id = 123456789 # Replace me!

[tokens]
discord = "REPLACE-ME"
github = ""
